# Generated by Django 5.0.1 on 2024-01-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_is_admin_user_is_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
