# Generated by Django 5.0.1 on 2024-02-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institutions', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('publish_date', models.DateField()),
                ('authors', models.JSONField(default=list)),
                ('abstract', models.TextField()),
                ('integral_text', models.TextField()),
                ('references', models.JSONField(default=list)),
            ],
        ),
    ]
