# Generated by Django 5.0.1 on 2024-02-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='endDate',
            field=models.DateField(default='2023-12-31'),
        ),
        migrations.AddField(
            model_name='article',
            name='startDate',
            field=models.DateField(default='2023-12-31'),
        ),
    ]
